### ISSUE TITLE
Resubmission Checklist

### ISSUE THREAD

**Issue by ShozenD** [MLGlobalHealth/bayes-rate-consistency#11]
# Resubmission Checklist

- [ ] #12
   - [x] Load experiment settings from .yml file
   - [ ] Save model output outside the repository
   - [ ] Rewrite experiment code

- [ ] Refactor R code
   - [x] sim-stan-utility.R
   - [x] sim-postprocess-diagnostic.R 
   - [ ] stan-utility.R
   - [ ] postprocess-diagnostic.R
   - [ ] postprocess-plotting.R
   - [ ] postprocess-diagnostic-single.R
   - [ ] postprocess-plotting-single.R

- [x] #17

- [ ] Additional Tables and Figures
  - [ ] The proportion of aggregate to individually reported contacts in each age and wave
  - [ ] Trace plots for the final model
  - [ ] Summary statistics for the final model
  - [x] #20
 
- [ ] Additional Experiments
  - [ ] How well can the model estimate age granular data from POLYMOD
  - [x] #21
  - [ ] Run a model where all data is restricted to new participants
