### ISSUE TITLE
Task List 2023-02-13

### ISSUE THREAD

**Issue by ShozenD** [MLGlobalHealth/bayes-rate-consistency#8]
### Task List
Things to do/implement for COVIMOD mtg on Feb. 23rd

- [x] #9
  - [x] Visualise the distribution of household size longitudinally
  - [x] Visualise the distribution of gaps

- [x] #10
  - [x] Run a basic GAM model on the first 10 waves 
  - [ ] Run longitudinal BRC model on the first 10 waves
